/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DENTAL_CLINIC_MANAGEMENT_SYSTEM;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JESSA MARIE BEBITA
 */
public class downloading extends javax.swing.JFrame {
private JFrame previousFrame;
    /**
     * Creates new form downloading
     */
    public downloading(JFrame previousFrame) {
        initComponents();
        this.previousFrame = previousFrame; 
       Thread t = new Thread(new Runnable() {
        @Override
        public void run() {
            try {
                for (int x = 0; x <= 100; x++) {
                    Thread.sleep(50); // Simulate loading delay
                    percent.setText(x + "%");
                    downloadbar.setValue(x );// Update percentage text
                }
                
                // Show confirmation dialog after loading completes
                JOptionPane.showMessageDialog(null, "Loading complete. Click OK BACK.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                 if (previousFrame != null) {
                    previousFrame.setVisible(true);
                 }
                // Show the homepage after user clicks OK
                // Close the downloading screen
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    });

    t.start(); 
            
        
        
    }

    private downloading() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        downloadbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Downloading");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        percent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        percent.setText("100%");
        getContentPane().add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, 40));

        downloadbar.setBackground(new java.awt.Color(0, 255, 255));
        downloadbar.setForeground(new java.awt.Color(0, 0, 153));
        downloadbar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(downloadbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 400, 50));

        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/another2doctor.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 550, 380));

        setSize(new java.awt.Dimension(561, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(downloading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(downloading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(downloading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(downloading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new downloading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar downloadbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel percent;
    // End of variables declaration//GEN-END:variables
}
