/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DENTAL_CLINIC_MANAGEMENT_SYSTEM;

import javax.swing.JFrame;

/**
 *
 * @author JESSA MARIE BEBITA
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage2q
     */
   
    public homepage() {
       
        initComponents();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        goappointment = new javax.swing.JButton();
        goschedule = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        gotreatment = new javax.swing.JButton();
        gobill = new javax.swing.JButton();
        goregistration = new javax.swing.JButton();
        gohistory = new javax.swing.JButton();
        gologout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOMEPAGE");
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 24)); // NOI18N
        jLabel1.setText("DENTAL CLINIC MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 270, 420, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel4.setText("Every smile tells a story ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 330, 90));

        jLabel5.setFont(new java.awt.Font("STLiti", 0, 24)); // NOI18N
        jLabel5.setText("let us make yours unforgettable");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 290, 50));

        goappointment.setText("BOOK  APPOINTMENT");
        goappointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goappointmentActionPerformed(evt);
            }
        });
        getContentPane().add(goappointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 170, -1));

        goschedule.setText("SCHEDULE");
        goschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(goschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 150, -1));

        gotreatment.setText("SERVICES");
        gotreatment.setBorder(null);
        gotreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotreatmentActionPerformed(evt);
            }
        });

        gobill.setText("BILL");
        gobill.setBorder(null);
        gobill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobillActionPerformed(evt);
            }
        });

        goregistration.setText("REGISTRATION");
        goregistration.setBorder(null);
        goregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goregistrationActionPerformed(evt);
            }
        });

        gohistory.setText("HISTORY");
        gohistory.setBorder(null);
        gohistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gohistoryActionPerformed(evt);
            }
        });

        gologout.setText("LOG OUT");
        gologout.setBorder(null);
        gologout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gologoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(goregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gotreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gobill, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gohistory, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(gologout, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gotreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gobill, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gohistory, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gologout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/homepagepic.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 850, 350));

        jLabel7.setFont(new java.awt.Font("SimSun-ExtG", 1, 36)); // NOI18N
        jLabel7.setText("DENTAL CLINIC MANAGEMENT SYSTEM");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 620, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("\"Healthy smiles start with great care your dental clinic is where confidence begins.\"");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 550, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stock-vector-seamless-vector-pattern-in-a-dental-linear-style-background-for-web-site-dental-clinic-518836648.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 840, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotreatmentActionPerformed
        // TODO add your handling code here:
        detailstreatment obj = new detailstreatment();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_gotreatmentActionPerformed

    private void gobillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobillActionPerformed
        // TODO add your handling code here:
        bill obj = new bill();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_gobillActionPerformed

    private void goregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goregistrationActionPerformed
        // TODO add your handling code here:
        registrationpage obj = new registrationpage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_goregistrationActionPerformed

    private void gohistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gohistoryActionPerformed
        // TODO add your handling code here:
        history obj = new history();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_gohistoryActionPerformed

    private void gologoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gologoutActionPerformed
        // TODO add your handling code here:
        loginpage obj = new loginpage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_gologoutActionPerformed

    private void goscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goscheduleActionPerformed
        // TODO add your handling code here:
        schedule obj = new schedule();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_goscheduleActionPerformed

    private void goappointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goappointmentActionPerformed
        // TODO add your handling code here:
       JFrame previous = new homepage(); // Example previous frame
       appointment app = new appointment(previous);
       app.setVisible(true);

    }//GEN-LAST:event_goappointmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goappointment;
    private javax.swing.JButton gobill;
    private javax.swing.JButton gohistory;
    private javax.swing.JButton gologout;
    private javax.swing.JButton goregistration;
    private javax.swing.JButton goschedule;
    private javax.swing.JButton gotreatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
